# 01 — Exploratory Data Analysis

MDQ 2026 — поиск скрытых предпринимателей среди физлиц.

Цель ноутбука: понять структуру данных, сравнить business vs consumer, проверить качество, подтвердить/опровергнуть гипотезы из `docs/FEATURES.md`.

In [1]:
# Импорты и настройка путей
import sys
from pathlib import Path

# Добавляем корень репо в sys.path чтобы импортировать src.config
ROOT = Path.cwd().parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import polars as pl
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

from src.config import (
    BUSINESS_CARDS_PATH, CONSUMER_CARDS_PATH, MERCHANTS_PATH,
    BUSINESS_HOURS_START, BUSINESS_HOURS_END,
    B2B_MCC_CODES, CONSUMER_MCC_CODES, RANDOM_STATE,
)

np.random.seed(RANDOM_STATE)
pl.Config.set_tbl_rows(20)
pl.Config.set_tbl_cols(20)
print('Polars version:', pl.__version__)

Polars version: 1.41.0

## 1. Загрузка данных

In [2]:
business = pl.read_parquet(BUSINESS_CARDS_PATH)
consumer = pl.read_parquet(CONSUMER_CARDS_PATH)
merchants = pl.read_parquet(MERCHANTS_PATH)

print(f'business : {business.shape}')
print(f'consumer : {consumer.shape}')
print(f'merchants: {merchants.shape}')

business : (2997593, 12)
consumer : (9832487, 12)
merchants: (2165, 5)

In [3]:
# Нормализуем имя поля is_recurring (в схеме CASE.md оно с большой буквы)
for name in ['business', 'consumer']:
    df = business if name == 'business' else consumer
    if 'Is_recurring' in df.columns and 'is_recurring' not in df.columns:
        df = df.rename({'Is_recurring': 'is_recurring'})
        if name == 'business':
            business = df
        else:
            consumer = df
print('business cols:', business.columns)
print('consumer cols:', consumer.columns)
print('merchants cols:', merchants.columns)

business cols: ['transaction_date', 'transaction_timestamp', 'transaction_amount_kzt', 'mcc', 'merchant_id', 'channel', 'bank_name', 'country', 'card_number', 'card_tier', 'tokenized', 'is_recurring']
consumer cols: ['transaction_date', 'transaction_timestamp', 'transaction_amount_kzt', 'mcc', 'merchant_id', 'channel', 'bank_name', 'country', 'card_number', 'card_tier', 'tokenized', 'is_recurring']
merchants cols: ['merchant_id', 'merchant_name', 'mcc', 'merchant_country', 'recurring_capable']

## 2. Базовый обзор каждого датасета

In [4]:
def overview(df: pl.DataFrame, name: str) -> None:
    """Печатает базовую статистику по датасету."""
    print(f'\n=== {name} ===')
    print(f'shape : {df.shape}')
    print('\n-- dtypes --')
    for col, dt in zip(df.columns, df.dtypes):
        print(f'  {col:30s} {dt}')
    print('\n-- null counts --')
    nulls = df.null_count().to_dicts()[0]
    any_null = False
    for col, n in nulls.items():
        if n > 0:
            print(f'  {col:30s} {n:>10,}')
            any_null = True
    if not any_null:
        print('  (no nulls)')

overview(business, 'business_cards')
overview(consumer, 'consumer_cards')
overview(merchants, 'merchants_reference')

=== business_cards ===
shape : (2997593, 12)

-- dtypes --
  transaction_date               Date
  transaction_timestamp          Datetime(time_unit='ms', time_zone=None)
  transaction_amount_kzt         Int64
  mcc                            String
  merchant_id                    String
  channel                        String
  bank_name                      String
  country                        String
  card_number                    String
  card_tier                      String
  tokenized                      Boolean
  is_recurring                   Boolean

-- null counts --
  (no nulls)

=== consumer_cards ===
shape : (9832487, 12)

-- dtypes --
  transaction_date               Date
  transaction_timestamp          Datetime(time_unit='ms', time_zone=None)
  transaction_amount_kzt         Int64
  mcc                            String
  merchant_id                    String
  channel                        String
  bank_name                      String
  country                        String
  card_number                    String
  card_tier                      String
  tokenized                      Boolean
  is_recurring                   Boolean

-- null counts --
  (no nulls)

=== merchants_reference ===
shape : (2165, 5)

-- dtypes --
  merchant_id                    String
  merchant_name                  String
  mcc                            String
  merchant_country               String
  recurring_capable              Boolean

-- null counts --
  (no nulls)

In [5]:
business.head(10)

shape: (10, 12)
┌────────┬────────┬────────┬──────┬────────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┐
│ transa ┆ transa ┆ transa ┆ mcc  ┆ mercha ┆ chann ┆ bank_ ┆ count ┆ card_ ┆ card_ ┆ token ┆ is_re │
│ ction_ ┆ ction_ ┆ ction_ ┆ ---  ┆ nt_id  ┆ el    ┆ name  ┆ ry    ┆ numbe ┆ tier  ┆ ized  ┆ curri │
│ date   ┆ timest ┆ amount ┆ str  ┆ ---    ┆ ---   ┆ ---   ┆ ---   ┆ r     ┆ ---   ┆ ---   ┆ ng    │
│ ---    ┆ amp    ┆ _kzt   ┆      ┆ str    ┆ str   ┆ str   ┆ str   ┆ ---   ┆ str   ┆ bool  ┆ ---   │
│ date   ┆ ---    ┆ ---    ┆      ┆        ┆       ┆       ┆       ┆ str   ┆       ┆       ┆ bool  │
│        ┆ dateti ┆ i64    ┆      ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ me[ms] ┆        ┆      ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
╞════════╪════════╪════════╪══════╪════════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╡
│ 2025-1 ┆ 2025-1 ┆ 180976 ┆ 7372 ┆ MER_00 ┆ onlin ┆ Kaspi ┆ US    ┆ 52285 ┆ Busin ┆ false ┆ true  │
│ 0-01   ┆ 0-01   ┆        ┆      ┆ 0007   ┆ e     ┆       ┆       ┆ 92291 ┆ ess   ┆       ┆       │
│        ┆ 00:00: ┆        ┆      ┆        ┆       ┆       ┆       ┆ 43884 ┆       ┆       ┆       │
│        ┆ 00     ┆        ┆      ┆        ┆       ┆       ┆       ┆ 5     ┆       ┆       ┆       │
│ 2025-1 ┆ 2025-1 ┆ 153206 ┆ 7372 ┆ MER_00 ┆ onlin ┆ Home  ┆ US    ┆ 52014 ┆ Busin ┆ false ┆ true  │
│ 0-01   ┆ 0-01   ┆        ┆      ┆ 0006   ┆ e     ┆ Credi ┆       ┆ 95142 ┆ ess   ┆       ┆       │
│        ┆ 00:00: ┆        ┆      ┆        ┆       ┆ t     ┆       ┆ 19337 ┆       ┆       ┆       │
│        ┆ 00     ┆        ┆      ┆        ┆       ┆ Bank  ┆       ┆ 2     ┆       ┆       ┆       │
│ 2025-1 ┆ 2025-1 ┆ 197106 ┆ 7372 ┆ MER_00 ┆ onlin ┆ Home  ┆ US    ┆ 52014 ┆ Busin ┆ false ┆ true  │
│ 0-01   ┆ 0-01   ┆        ┆      ┆ 0007   ┆ e     ┆ Credi ┆       ┆ 92177 ┆ ess   ┆       ┆       │
│        ┆ 00:00: ┆        ┆      ┆        ┆       ┆ t     ┆       ┆ 67728 ┆       ┆       ┆       │
│        ┆ 00     ┆        ┆      ┆        ┆       ┆ Bank  ┆       ┆ 8     ┆       ┆       ┆       │
│ 2025-1 ┆ 2025-1 ┆ 189598 ┆ 7372 ┆ MER_00 ┆ onlin ┆ Kaspi ┆ US    ┆ 51765 ┆ Busin ┆ false ┆ true  │
│ 0-01   ┆ 0-01   ┆        ┆      ┆ 0008   ┆ e     ┆       ┆       ┆ 13443 ┆ ess   ┆       ┆       │
│        ┆ 00:01: ┆        ┆      ┆        ┆       ┆       ┆       ┆ 69763 ┆       ┆       ┆       │
│        ┆ 00     ┆        ┆      ┆        ┆       ┆       ┆       ┆ 5     ┆       ┆       ┆       │
│ 2025-1 ┆ 2025-1 ┆ 700571 ┆ 7311 ┆ MER_00 ┆ onlin ┆ Halyk ┆ Russi ┆ 51006 ┆ Busin ┆ false ┆ true  │
│ 0-01   ┆ 0-01   ┆        ┆      ┆ 0003   ┆ e     ┆       ┆ a     ┆ 11967 ┆ ess   ┆       ┆       │
│        ┆ 00:03: ┆        ┆      ┆        ┆       ┆       ┆       ┆ 45552 ┆       ┆       ┆       │
│        ┆ 00     ┆        ┆      ┆        ┆       ┆       ┆       ┆ 0     ┆       ┆       ┆       │
│ 2025-1 ┆ 2025-1 ┆ 228899 ┆ 7372 ┆ MER_00 ┆ onlin ┆ Euras ┆ US    ┆ 54410 ┆ Busin ┆ false ┆ true  │
│ 0-01   ┆ 0-01   ┆        ┆      ┆ 0009   ┆ e     ┆ ian   ┆       ┆ 26246 ┆ ess   ┆       ┆       │
│        ┆ 00:04: ┆        ┆      ┆        ┆       ┆ Bank  ┆       ┆ 19953 ┆       ┆       ┆       │
│        ┆ 00     ┆        ┆      ┆        ┆       ┆       ┆       ┆ 4     ┆       ┆       ┆       │
│ 2025-1 ┆ 2025-1 ┆ 206896 ┆ 7372 ┆ MER_00 ┆ onlin ┆ Euras ┆ US    ┆ 54410 ┆ Busin ┆ false ┆ true  │
│ 0-01   ┆ 0-01   ┆        ┆      ┆ 0009   ┆ e     ┆ ian   ┆       ┆ 29193 ┆ ess   ┆       ┆       │
│        ┆ 00:05: ┆        ┆      ┆        ┆       ┆ Bank  ┆       ┆ 73926 ┆       ┆       ┆       │
│        ┆ 00     ┆        ┆      ┆        ┆       ┆       ┆       ┆ 0     ┆       ┆       ┆       │
│ 2025-1 ┆ 2025-1 ┆ 391854 ┆ 7311 ┆ MER_00 ┆ onlin ┆ Halyk ┆ Singa ┆ 51006 ┆ Busin ┆ false ┆ true  │
│ 0-01   ┆ 0-01   ┆        ┆      ┆ 0002   ┆ e     ┆       ┆ pore  ┆ 10143 ┆ ess   ┆       ┆       │
│        ┆ 00:06: ┆        ┆      ┆        ┆       ┆       ┆       ┆ 74849 ┆       ┆       ┆       │
│        ┆ 00     ┆        ┆      ┆        ┆       ┆       ┆       ┆ 3     ┆       ┆       ┆       │
│ 2025-1 ┆ 2025-1 ┆ 315274 ┆ 4816 ┆ MER_00 ┆ onlin ┆ Euras ┆ Kazak ┆ 54410 ┆ Busin ┆ false ┆ true  │
│ 0-01   ┆ 0-01   ┆        ┆      ┆ 0883   ┆ e     ┆ ian   ┆ hstan ┆ 24234 ┆ ess   ┆       ┆       │
│        ┆ 00:07: ┆        ┆      ┆        ┆       ┆ Bank  ┆       ┆ 54297 ┆       ┆       ┆       │
│        ┆ 00     ┆        ┆      ┆        ┆       ┆       ┆       ┆ 1     ┆       ┆       ┆       │
│ 2025-1 ┆ 2025-1 ┆ 347286 ┆ 7311 ┆ MER_00 ┆ onlin ┆ Kaspi ┆ Irela ┆ 55315 ┆ Busin ┆ false ┆ true  │
│ 0-01   ┆ 0-01   ┆        ┆      ┆ 0004   ┆ e     ┆       ┆ nd    ┆ 13353 ┆ ess   ┆       ┆       │
│        ┆ 00:08: ┆        ┆      ┆        ┆       ┆       ┆       ┆ 46022 ┆       ┆       ┆       │
│        ┆ 00     ┆        ┆      ┆        ┆       ┆       ┆       ┆ 2     ┆       ┆       ┆       │
└────────┴────────┴────────┴──────┴────────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┘

In [6]:
consumer.head(10)

shape: (10, 12)
┌────────┬────────┬────────┬──────┬────────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┐
│ transa ┆ transa ┆ transa ┆ mcc  ┆ mercha ┆ chann ┆ bank_ ┆ count ┆ card_ ┆ card_ ┆ token ┆ is_re │
│ ction_ ┆ ction_ ┆ ction_ ┆ ---  ┆ nt_id  ┆ el    ┆ name  ┆ ry    ┆ numbe ┆ tier  ┆ ized  ┆ curri │
│ date   ┆ timest ┆ amount ┆ str  ┆ ---    ┆ ---   ┆ ---   ┆ ---   ┆ r     ┆ ---   ┆ ---   ┆ ng    │
│ ---    ┆ amp    ┆ _kzt   ┆      ┆ str    ┆ str   ┆ str   ┆ str   ┆ ---   ┆ str   ┆ bool  ┆ ---   │
│ date   ┆ ---    ┆ ---    ┆      ┆        ┆       ┆       ┆       ┆ str   ┆       ┆       ┆ bool  │
│        ┆ dateti ┆ i64    ┆      ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆ me[ms] ┆        ┆      ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
╞════════╪════════╪════════╪══════╪════════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╡
│ 2025-1 ┆ 2025-1 ┆ 4788   ┆ 4814 ┆ MER_00 ┆ onlin ┆ Alata ┆ Kazak ┆ 52639 ┆ Stand ┆ false ┆ true  │
│ 0-01   ┆ 0-01   ┆        ┆      ┆ 0064   ┆ e     ┆ u     ┆ hstan ┆ 07968 ┆ ard   ┆       ┆       │
│        ┆ 00:04: ┆        ┆      ┆        ┆       ┆ City  ┆       ┆ 82459 ┆       ┆       ┆       │
│        ┆ 00     ┆        ┆      ┆        ┆       ┆ Bank  ┆       ┆ 6     ┆       ┆       ┆       │
│ 2025-1 ┆ 2025-1 ┆ 5240   ┆ 4814 ┆ MER_00 ┆ onlin ┆ Bank  ┆ Kazak ┆ 51190 ┆ Stand ┆ false ┆ true  │
│ 0-01   ┆ 0-01   ┆        ┆      ┆ 0063   ┆ e     ┆ RBK   ┆ hstan ┆ 23663 ┆ ard   ┆       ┆       │
│        ┆ 00:10: ┆        ┆      ┆        ┆       ┆       ┆       ┆ 98498 ┆       ┆       ┆       │
│        ┆ 00     ┆        ┆      ┆        ┆       ┆       ┆       ┆ 6     ┆       ┆       ┆       │
│ 2025-1 ┆ 2025-1 ┆ 4576   ┆ 4814 ┆ MER_00 ┆ onlin ┆ Kaspi ┆ Kazak ┆ 52285 ┆ Stand ┆ false ┆ true  │
│ 0-01   ┆ 0-01   ┆        ┆      ┆ 0066   ┆ e     ┆       ┆ hstan ┆ 90878 ┆ ard   ┆       ┆       │
│        ┆ 00:12: ┆        ┆      ┆        ┆       ┆       ┆       ┆ 15515 ┆       ┆       ┆       │
│        ┆ 00     ┆        ┆      ┆        ┆       ┆       ┆       ┆ 4     ┆       ┆       ┆       │
│ 2025-1 ┆ 2025-1 ┆ 6078   ┆ 4814 ┆ MER_00 ┆ onlin ┆ Home  ┆ Kazak ┆ 53384 ┆ Stand ┆ false ┆ true  │
│ 0-01   ┆ 0-01   ┆        ┆      ┆ 0063   ┆ e     ┆ Credi ┆ hstan ┆ 72125 ┆ ard   ┆       ┆       │
│        ┆ 00:37: ┆        ┆      ┆        ┆       ┆ t     ┆       ┆ 33369 ┆       ┆       ┆       │
│        ┆ 00     ┆        ┆      ┆        ┆       ┆ Bank  ┆       ┆ 3     ┆       ┆       ┆       │
│ 2025-1 ┆ 2025-1 ┆ 6042   ┆ 4814 ┆ MER_00 ┆ onlin ┆ Kaspi ┆ Kazak ┆ 55315 ┆ Afflu ┆ false ┆ true  │
│ 0-01   ┆ 0-01   ┆        ┆      ┆ 0065   ┆ e     ┆       ┆ hstan ┆ 14712 ┆ ent   ┆       ┆       │
│        ┆ 00:37: ┆        ┆      ┆        ┆       ┆       ┆       ┆ 39455 ┆       ┆       ┆       │
│        ┆ 00     ┆        ┆      ┆        ┆       ┆       ┆       ┆ 7     ┆       ┆       ┆       │
│ 2025-1 ┆ 2025-1 ┆ 137960 ┆ 7995 ┆ MER_00 ┆ onlin ┆ Kaspi ┆ Kazak ┆ 51765 ┆ Stand ┆ true  ┆ false │
│ 0-01   ┆ 0-01   ┆        ┆      ┆ 0849   ┆ e     ┆       ┆ hstan ┆ 12180 ┆ ard   ┆       ┆       │
│        ┆ 00:46: ┆        ┆      ┆        ┆       ┆       ┆       ┆ 84117 ┆       ┆       ┆       │
│        ┆ 17     ┆        ┆      ┆        ┆       ┆       ┆       ┆ 4     ┆       ┆       ┆       │
│ 2025-1 ┆ 2025-1 ┆ 122057 ┆ 5099 ┆ MER_00 ┆ onlin ┆ Euras ┆ Kazak ┆ 54410 ┆ Afflu ┆ true  ┆ false │
│ 0-01   ┆ 0-01   ┆        ┆      ┆ 1015   ┆ e     ┆ ian   ┆ hstan ┆ 20083 ┆ ent   ┆       ┆       │
│        ┆ 00:53: ┆        ┆      ┆        ┆       ┆ Bank  ┆       ┆ 06340 ┆       ┆       ┆       │
│        ┆ 07     ┆        ┆      ┆        ┆       ┆       ┆       ┆ 8     ┆       ┆       ┆       │
│ 2025-1 ┆ 2025-1 ┆ 226475 ┆ 8211 ┆ MER_00 ┆ onlin ┆ Bank  ┆ Kazak ┆ 51190 ┆ Stand ┆ false ┆ false │
│ 0-01   ┆ 0-01   ┆        ┆      ┆ 0606   ┆ e     ┆ RBK   ┆ hstan ┆ 23509 ┆ ard   ┆       ┆       │
│        ┆ 01:15: ┆        ┆      ┆        ┆       ┆       ┆       ┆ 21107 ┆       ┆       ┆       │
│        ┆ 53     ┆        ┆      ┆        ┆       ┆       ┆       ┆ 3     ┆       ┆       ┆       │
│ 2025-1 ┆ 2025-1 ┆ 4274   ┆ 4814 ┆ MER_00 ┆ onlin ┆ Kaspi ┆ Kazak ┆ 52285 ┆ Stand ┆ false ┆ true  │
│ 0-01   ┆ 0-01   ┆        ┆      ┆ 0066   ┆ e     ┆       ┆ hstan ┆ 98880 ┆ ard   ┆       ┆       │
│        ┆ 01:36: ┆        ┆      ┆        ┆       ┆       ┆       ┆ 63692 ┆       ┆       ┆       │
│        ┆ 00     ┆        ┆      ┆        ┆       ┆       ┆       ┆ 1     ┆       ┆       ┆       │
│ 2025-1 ┆ 2025-1 ┆ 4270   ┆ 4814 ┆ MER_00 ┆ onlin ┆ Kaspi ┆ Kazak ┆ 52285 ┆ Stand ┆ false ┆ true  │
│ 0-01   ┆ 0-01   ┆        ┆      ┆ 0066   ┆ e     ┆       ┆ hstan ┆ 93374 ┆ ard   ┆       ┆       │
│        ┆ 02:24: ┆        ┆      ┆        ┆       ┆       ┆       ┆ 61775 ┆       ┆       ┆       │
│        ┆ 00     ┆        ┆      ┆        ┆       ┆       ┆       ┆ 0     ┆       ┆       ┆       │
└────────┴────────┴────────┴──────┴────────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┘

In [7]:
merchants.head(10)

shape: (10, 5)
┌─────────────┬─────────────────────┬──────┬──────────────────┬───────────────────┐
│ merchant_id ┆ merchant_name       ┆ mcc  ┆ merchant_country ┆ recurring_capable │
│ ---         ┆ ---                 ┆ ---  ┆ ---              ┆ ---               │
│ str         ┆ str                 ┆ str  ┆ str              ┆ bool              │
╞═════════════╪═════════════════════╪══════╪══════════════════╪═══════════════════╡
│ MER_000000  ┆ Google Ads          ┆ 7311 ┆ Ireland          ┆ true              │
│ MER_000001  ┆ Meta Ads            ┆ 7311 ┆ Ireland          ┆ true              │
│ MER_000002  ┆ TikTok Ads          ┆ 7311 ┆ Singapore        ┆ true              │
│ MER_000003  ┆ Yandex Direct       ┆ 7311 ┆ Russia           ┆ true              │
│ MER_000004  ┆ LinkedIn Ads        ┆ 7311 ┆ Ireland          ┆ true              │
│ MER_000005  ┆ Instagram Promote   ┆ 7311 ┆ Ireland          ┆ true              │
│ MER_000006  ┆ Amazon Web Services ┆ 7372 ┆ US               ┆ true              │
│ MER_000007  ┆ Microsoft Azure     ┆ 7372 ┆ US               ┆ true              │
│ MER_000008  ┆ Google Cloud        ┆ 7372 ┆ US               ┆ true              │
│ MER_000009  ┆ Salesforce          ┆ 7372 ┆ US               ┆ true              │
└─────────────┴─────────────────────┴──────┴──────────────────┴───────────────────┘

In [8]:
business.describe()

shape: (9, 13)
┌─────┬─────┬─────┬────────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┐
│ sta ┆ tra ┆ tra ┆ transa ┆ mcc   ┆ merch ┆ chann ┆ bank_ ┆ count ┆ card_ ┆ card_ ┆ token ┆ is_re │
│ tis ┆ nsa ┆ nsa ┆ ction_ ┆ ---   ┆ ant_i ┆ el    ┆ name  ┆ ry    ┆ numbe ┆ tier  ┆ ized  ┆ curri │
│ tic ┆ cti ┆ cti ┆ amount ┆ str   ┆ d     ┆ ---   ┆ ---   ┆ ---   ┆ r     ┆ ---   ┆ ---   ┆ ng    │
│ --- ┆ on_ ┆ on_ ┆ _kzt   ┆       ┆ ---   ┆ str   ┆ str   ┆ str   ┆ ---   ┆ str   ┆ f64   ┆ ---   │
│ str ┆ dat ┆ tim ┆ ---    ┆       ┆ str   ┆       ┆       ┆       ┆ str   ┆       ┆       ┆ f64   │
│     ┆ e   ┆ est ┆ f64    ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ --- ┆ amp ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ str ┆ --- ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆ str ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
╞═════╪═════╪═════╪════════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╡
│ cou ┆ 299 ┆ 299 ┆ 2.9975 ┆ 29975 ┆ 29975 ┆ 29975 ┆ 29975 ┆ 29975 ┆ 29975 ┆ 29975 ┆ 2.997 ┆ 2.997 │
│ nt  ┆ 759 ┆ 759 ┆ 93e6   ┆ 93    ┆ 93    ┆ 93    ┆ 93    ┆ 93    ┆ 93    ┆ 93    ┆ 593e6 ┆ 593e6 │
│     ┆ 3   ┆ 3   ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ nul ┆ 0   ┆ 0   ┆ 0.0    ┆ 0     ┆ 0     ┆ 0     ┆ 0     ┆ 0     ┆ 0     ┆ 0     ┆ 0.0   ┆ 0.0   │
│ l_c ┆     ┆     ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ oun ┆     ┆     ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ t   ┆     ┆     ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ mea ┆ 202 ┆ 202 ┆ 156535 ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ 0.600 ┆ 0.133 │
│ n   ┆ 6-0 ┆ 6-0 ┆ .27468 ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 008   ┆ 447   │
│     ┆ 1-0 ┆ 1-0 ┆ 1      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ 1   ┆ 1   ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ 10: ┆ 23: ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ 57: ┆ 22: ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ 48. ┆ 32. ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ 976 ┆ 938 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ 075 ┆ 000 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ std ┆ nul ┆ nul ┆ 252868 ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  │
│     ┆ l   ┆ l   ┆ .24236 ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ min ┆ 202 ┆ 202 ┆ 67.0   ┆ 2741  ┆ MER_0 ┆ POS   ┆ Alata ┆ Austr ┆ 51006 ┆ Busin ┆ 0.0   ┆ 0.0   │
│     ┆ 5-1 ┆ 5-1 ┆        ┆       ┆ 00000 ┆       ┆ u     ┆ alia  ┆ 10003 ┆ ess   ┆       ┆       │
│     ┆ 0-0 ┆ 0-0 ┆        ┆       ┆       ┆       ┆ City  ┆       ┆ 02508 ┆       ┆       ┆       │
│     ┆ 1   ┆ 1   ┆        ┆       ┆       ┆       ┆ Bank  ┆       ┆ 1     ┆       ┆       ┆       │
│     ┆     ┆ 00: ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆ 00: ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆ 00  ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ 25% ┆ 202 ┆ 202 ┆ 22835. ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  │
│     ┆ 5-1 ┆ 5-1 ┆ 0      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ 1-1 ┆ 1-1 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ 7   ┆ 7   ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆ 15: ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆ 42: ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆ 00  ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ 50% ┆ 202 ┆ 202 ┆ 77224. ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  │
│     ┆ 6-0 ┆ 6-0 ┆ 0      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ 1-0 ┆ 1-0 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ 1   ┆ 1   ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆ 13: ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆ 32: ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆ 36  ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ 75% ┆ 202 ┆ 202 ┆ 196081 ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  │
│     ┆ 6-0 ┆ 6-0 ┆ .0     ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ 2-1 ┆ 2-1 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ 7   ┆ 7   ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆ 16: ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆ 16: ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆ 51  ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ max ┆ 202 ┆ 202 ┆ 4.0799 ┆ 8931  ┆ MER_0 ┆ onlin ┆ Kaspi ┆ Uzbek ┆ 55315 ┆ Busin ┆ 1.0   ┆ 1.0   │
│     ┆ 6-0 ┆ 6-0 ┆ 297e7  ┆       ┆ 02153 ┆ e     ┆       ┆ istan ┆ 19996 ┆ ess   ┆       ┆       │
│     ┆ 3-3 ┆ 3-3 ┆        ┆       ┆       ┆       ┆       ┆       ┆ 14914 ┆       ┆       ┆       │
│     ┆ 1   ┆ 1   ┆        ┆       ┆       ┆       ┆       ┆       ┆ 8     ┆       ┆       ┆       │
│     ┆     ┆ 23: ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆ 59: ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆ 53  ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
└─────┴─────┴─────┴────────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┘

In [9]:
consumer.describe()

shape: (9, 13)
┌─────┬─────┬─────┬────────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┐
│ sta ┆ tra ┆ tra ┆ transa ┆ mcc   ┆ merch ┆ chann ┆ bank_ ┆ count ┆ card_ ┆ card_ ┆ token ┆ is_re │
│ tis ┆ nsa ┆ nsa ┆ ction_ ┆ ---   ┆ ant_i ┆ el    ┆ name  ┆ ry    ┆ numbe ┆ tier  ┆ ized  ┆ curri │
│ tic ┆ cti ┆ cti ┆ amount ┆ str   ┆ d     ┆ ---   ┆ ---   ┆ ---   ┆ r     ┆ ---   ┆ ---   ┆ ng    │
│ --- ┆ on_ ┆ on_ ┆ _kzt   ┆       ┆ ---   ┆ str   ┆ str   ┆ str   ┆ ---   ┆ str   ┆ f64   ┆ ---   │
│ str ┆ dat ┆ tim ┆ ---    ┆       ┆ str   ┆       ┆       ┆       ┆ str   ┆       ┆       ┆ f64   │
│     ┆ e   ┆ est ┆ f64    ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ --- ┆ amp ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ str ┆ --- ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆ str ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
╞═════╪═════╪═════╪════════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╡
│ cou ┆ 983 ┆ 983 ┆ 9.8324 ┆ 98324 ┆ 98324 ┆ 98324 ┆ 98324 ┆ 98324 ┆ 98324 ┆ 98324 ┆ 9.832 ┆ 9.832 │
│ nt  ┆ 248 ┆ 248 ┆ 87e6   ┆ 87    ┆ 87    ┆ 87    ┆ 87    ┆ 87    ┆ 87    ┆ 87    ┆ 487e6 ┆ 487e6 │
│     ┆ 7   ┆ 7   ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ nul ┆ 0   ┆ 0   ┆ 0.0    ┆ 0     ┆ 0     ┆ 0     ┆ 0     ┆ 0     ┆ 0     ┆ 0     ┆ 0.0   ┆ 0.0   │
│ l_c ┆     ┆     ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ oun ┆     ┆     ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ t   ┆     ┆     ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ mea ┆ 202 ┆ 202 ┆ 54045. ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ 0.386 ┆ 0.027 │
│ n   ┆ 5-1 ┆ 5-1 ┆ 424791 ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 253   ┆ 18    │
│     ┆ 2-3 ┆ 2-3 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ 0   ┆ 0   ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ 02: ┆ 17: ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ 12: ┆ 42: ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ 35. ┆ 42. ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ 726 ┆ 777 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ 033 ┆ 000 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ std ┆ nul ┆ nul ┆ 169654 ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  │
│     ┆ l   ┆ l   ┆ .62722 ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆     ┆ 9      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ min ┆ 202 ┆ 202 ┆ 15.0   ┆ 0780  ┆ MER_0 ┆ POS   ┆ Alata ┆ Austr ┆ 51006 ┆ Afflu ┆ 0.0   ┆ 0.0   │
│     ┆ 5-1 ┆ 5-1 ┆        ┆       ┆ 00000 ┆       ┆ u     ┆ alia  ┆ 10005 ┆ ent   ┆       ┆       │
│     ┆ 0-0 ┆ 0-0 ┆        ┆       ┆       ┆       ┆ City  ┆       ┆ 93096 ┆       ┆       ┆       │
│     ┆ 1   ┆ 1   ┆        ┆       ┆       ┆       ┆ Bank  ┆       ┆ 5     ┆       ┆       ┆       │
│     ┆     ┆ 00: ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆ 00: ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆ 00  ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ 25% ┆ 202 ┆ 202 ┆ 4172.0 ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  │
│     ┆ 5-1 ┆ 5-1 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ 1-1 ┆ 1-1 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ 6   ┆ 6   ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆ 23: ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆ 02: ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆ 47  ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ 50% ┆ 202 ┆ 202 ┆ 11892. ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  │
│     ┆ 5-1 ┆ 5-1 ┆ 0      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ 2-2 ┆ 2-2 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ 8   ┆ 8   ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆ 09: ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆ 27: ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆ 40  ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ 75% ┆ 202 ┆ 202 ┆ 39665. ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  │
│     ┆ 6-0 ┆ 6-0 ┆ 0      ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ 2-1 ┆ 2-1 ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆ 3   ┆ 3   ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆ 18: ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆ 44: ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆ 31  ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ max ┆ 202 ┆ 202 ┆ 3.1971 ┆ 9700  ┆ MER_0 ┆ onlin ┆ Kaspi ┆ Uzbek ┆ 55315 ┆ Stand ┆ 1.0   ┆ 1.0   │
│     ┆ 6-0 ┆ 6-0 ┆ 032e7  ┆       ┆ 02164 ┆ e     ┆       ┆ istan ┆ 19994 ┆ ard   ┆       ┆       │
│     ┆ 3-3 ┆ 3-3 ┆        ┆       ┆       ┆       ┆       ┆       ┆ 94393 ┆       ┆       ┆       │
│     ┆ 1   ┆ 1   ┆        ┆       ┆       ┆       ┆       ┆       ┆ 0     ┆       ┆       ┆       │
│     ┆     ┆ 23: ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆ 59: ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│     ┆     ┆ 49  ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
└─────┴─────┴─────┴────────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┘

In [10]:
merchants.describe()

shape: (9, 6)
┌────────────┬─────────────┬─────────────────────────┬──────┬──────────────────┬───────────────────┐
│ statistic  ┆ merchant_id ┆ merchant_name           ┆ mcc  ┆ merchant_country ┆ recurring_capable │
│ ---        ┆ ---         ┆ ---                     ┆ ---  ┆ ---              ┆ ---               │
│ str        ┆ str         ┆ str                     ┆ str  ┆ str              ┆ f64               │
╞════════════╪═════════════╪═════════════════════════╪══════╪══════════════════╪═══════════════════╡
│ count      ┆ 2165        ┆ 2165                    ┆ 2165 ┆ 2165             ┆ 2165.0            │
│ null_count ┆ 0           ┆ 0                       ┆ 0    ┆ 0                ┆ 0.0               │
│ mean       ┆ null        ┆ null                    ┆ null ┆ null             ┆ 0.012471          │
│ std        ┆ null        ┆ null                    ┆ null ┆ null             ┆ null              │
│ min        ┆ MER_000000  ┆ Accounting/Auditin_3186 ┆ 0780 ┆ Australia        ┆ 0.0               │
│ 25%        ┆ null        ┆ null                    ┆ null ┆ null             ┆ null              │
│ 50%        ┆ null        ┆ null                    ┆ null ┆ null             ┆ null              │
│ 75%        ┆ null        ┆ null                    ┆ null ┆ null             ┆ null              │
│ max        ┆ MER_002164  ┆ inDrive                 ┆ 9700 ┆ US               ┆ 1.0               │
└────────────┴─────────────┴─────────────────────────┴──────┴──────────────────┴───────────────────┘

## 3. Сравнение business vs consumer

Все графики строим в Plotly. Для распределений берём sample транзакций — на полном объёме гистограммы рисуются долго.

### 3.1 Распределение transaction_amount_kzt (log scale)

In [12]:
# Сэмплируем по 300K транзакций из каждого класса — гистограмма не теряет форму
SAMPLE_N = 300_000
b_sample = business.sample(n=min(SAMPLE_N, business.height), seed=RANDOM_STATE)
c_sample = consumer.sample(n=min(SAMPLE_N, consumer.height), seed=RANDOM_STATE)

amt_df = pl.concat([
    b_sample.select(pl.col('transaction_amount_kzt')).with_columns(pl.lit('business').alias('card_type')),
    c_sample.select(pl.col('transaction_amount_kzt')).with_columns(pl.lit('consumer').alias('card_type')),
]).filter(pl.col('transaction_amount_kzt') > 0).to_pandas()

fig = px.histogram(
    amt_df, x='transaction_amount_kzt', color='card_type',
    nbins=80, log_x=True, log_y=True, barmode='overlay', opacity=0.55,
    title='Распределение transaction_amount_kzt (log-log, sample 300K на класс)',
)
fig.update_layout(xaxis_title='Сумма транзакции, ₸ (log)', yaxis_title='Частота (log)')
fig.show()

### 3.2 Агрегаты на уровне карты

In [13]:
# Считаем по каждой карте: n_tx, n_unique_merchants, n_unique_mcc, online_share, tokenized_share, recurring_share
def card_aggregates(df: pl.DataFrame, label: str) -> pl.DataFrame:
    return (
        df.group_by('card_number').agg([
            pl.len().alias('n_tx'),
            pl.col('merchant_id').n_unique().alias('n_unique_merchants'),
            pl.col('mcc').n_unique().alias('n_unique_mcc'),
            (pl.col('channel') == 'online').mean().alias('online_share'),
            pl.col('tokenized').cast(pl.Float64).mean().alias('tokenized_share'),
            pl.col('is_recurring').cast(pl.Float64).mean().alias('recurring_share'),
            pl.col('transaction_amount_kzt').sum().alias('total_spend'),
        ])
        .with_columns(pl.lit(label).alias('card_type'))
    )

b_cards = card_aggregates(business, 'business')
c_cards = card_aggregates(consumer, 'consumer')
cards = pl.concat([b_cards, c_cards])
print('Карт всего:', cards.shape)
cards.group_by('card_type').agg([
    pl.col('n_tx').median().alias('median_n_tx'),
    pl.col('n_unique_merchants').median().alias('median_n_merch'),
    pl.col('n_unique_mcc').median().alias('median_n_mcc'),
    pl.col('online_share').mean().alias('mean_online_share'),
    pl.col('tokenized_share').mean().alias('mean_tokenized'),
    pl.col('recurring_share').mean().alias('mean_recurring'),
    pl.col('total_spend').median().alias('median_total_spend'),
])

Карт всего: (105000, 9)

shape: (2, 8)
┌───────────┬────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┐
│ card_type ┆ median_n_t ┆ median_n_m ┆ median_n_m ┆ mean_onli ┆ mean_toke ┆ mean_recu ┆ median_to │
│ ---       ┆ x          ┆ erch       ┆ cc         ┆ ne_share  ┆ nized     ┆ rring     ┆ tal_spend │
│ str       ┆ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆ f64        ┆ f64        ┆ f64        ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞═══════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ consumer  ┆ 120.0      ┆ 37.0       ┆ 32.0       ┆ 0.468678  ┆ 0.38478   ┆ 0.031421  ┆ 2.976294e │
│           ┆            ┆            ┆            ┆           ┆           ┆           ┆ 6         │
│ business  ┆ 119.0      ┆ 16.0       ┆ 15.0       ┆ 0.848435  ┆ 0.584569  ┆ 0.1547    ┆ 1.7715e7  │
└───────────┴────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┘

In [14]:
# Боксплоты сравнения на уровне карты (log y где имеет смысл)
cards_pd = cards.to_pandas()
metrics = [
    ('n_tx', 'Транзакций на карту', True),
    ('n_unique_merchants', 'Уникальных мерчантов', True),
    ('n_unique_mcc', 'Уникальных MCC', False),
]
fig = make_subplots(rows=1, cols=3, subplot_titles=[m[1] for m in metrics])
for i, (col, _title, logy) in enumerate(metrics, start=1):
    for ct, color in [('business', '#1f77b4'), ('consumer', '#ff7f0e')]:
        fig.add_trace(
            go.Box(y=cards_pd.loc[cards_pd['card_type'] == ct, col],
                   name=ct, marker_color=color, showlegend=(i == 1)),
            row=1, col=i,
        )
    if logy:
        fig.update_yaxes(type='log', row=1, col=i)
fig.update_layout(height=420, title_text='Card-level метрики: business vs consumer')
fig.show()

In [15]:
# Доли (online / tokenized / recurring) — средние по картам
share_df = (
    cards.group_by('card_type').agg([
        pl.col('online_share').mean(),
        pl.col('tokenized_share').mean(),
        pl.col('recurring_share').mean(),
    ])
    .unpivot(index='card_type', variable_name='metric', value_name='share')
    .to_pandas()
)
fig = px.bar(share_df, x='metric', y='share', color='card_type', barmode='group',
             title='Средние доли: online / tokenized / recurring (по картам)')
fig.update_layout(yaxis_tickformat='.0%')
fig.show()

### 3.3 Топ-20 MCC у business vs consumer

In [16]:
def top_mcc(df: pl.DataFrame, k: int = 20) -> pl.DataFrame:
    return (
        df.group_by('mcc').agg(pl.len().alias('n_tx'))
          .sort('n_tx', descending=True)
          .head(k)
    )

top_b = top_mcc(business).with_columns(pl.lit('business').alias('card_type'))
top_c = top_mcc(consumer).with_columns(pl.lit('consumer').alias('card_type'))
top_mcc_df = pl.concat([top_b, top_c]).to_pandas()
top_mcc_df['mcc'] = top_mcc_df['mcc'].astype(str)

fig = px.bar(top_mcc_df, x='mcc', y='n_tx', color='card_type', barmode='group',
             title='Топ-20 MCC по количеству транзакций (business vs consumer)')
fig.update_layout(xaxis={'categoryorder': 'total descending'})
fig.show()

### 3.4 Временные паттерны — часы дня, дни недели, месяцы

In [17]:
def add_time_parts(df: pl.DataFrame) -> pl.DataFrame:
    return df.with_columns([
        pl.col('transaction_timestamp').dt.hour().alias('hour'),
        pl.col('transaction_timestamp').dt.weekday().alias('dow'),
        pl.col('transaction_timestamp').dt.truncate('1mo').alias('month'),
    ])

b_t = add_time_parts(business)
c_t = add_time_parts(consumer)

def share_by(df: pl.DataFrame, col: str, label: str) -> pl.DataFrame:
    total = df.height
    return (df.group_by(col).agg(pl.len().alias('n'))
              .with_columns([(pl.col('n') / total).alias('share'),
                             pl.lit(label).alias('card_type')])
              .sort(col))

hours = pl.concat([share_by(b_t, 'hour', 'business'),
                   share_by(c_t, 'hour', 'consumer')]).to_pandas()
fig = px.line(hours, x='hour', y='share', color='card_type', markers=True,
              title='Распределение транзакций по часам дня')
fig.add_vrect(x0=BUSINESS_HOURS_START, x1=BUSINESS_HOURS_END,
              fillcolor='lightgreen', opacity=0.2, line_width=0,
              annotation_text='Рабочие часы')
fig.update_layout(yaxis_tickformat='.1%')
fig.show()

In [18]:
dow = pl.concat([share_by(b_t, 'dow', 'business'),
                 share_by(c_t, 'dow', 'consumer')]).to_pandas()
dow_names = {1: 'Пн', 2: 'Вт', 3: 'Ср', 4: 'Чт', 5: 'Пт', 6: 'Сб', 7: 'Вс'}
dow['day'] = dow['dow'].map(dow_names)
fig = px.bar(dow, x='day', y='share', color='card_type', barmode='group',
             category_orders={'day': list(dow_names.values())},
             title='Распределение транзакций по дням недели')
fig.update_layout(yaxis_tickformat='.1%')
fig.show()

In [19]:
month = pl.concat([share_by(b_t, 'month', 'business'),
                   share_by(c_t, 'month', 'consumer')]).to_pandas()
fig = px.line(month, x='month', y='share', color='card_type', markers=True,
              title='Распределение транзакций по месяцам (10.2025 — 03.2026)')
fig.update_layout(yaxis_tickformat='.1%')
fig.show()

## 4. Анализ мерчантов

In [20]:
def top_merchants(df: pl.DataFrame, k: int = 20) -> pl.DataFrame:
    return (
        df.group_by('merchant_id').agg(pl.len().alias('n_tx'))
          .sort('n_tx', descending=True)
          .head(k)
          .join(merchants.select(['merchant_id', 'merchant_name', 'mcc']),
                on='merchant_id', how='left')
    )

top_b_m = top_merchants(business)
top_c_m = top_merchants(consumer)
print('Топ-20 мерчантов у business:')
print(top_b_m)
print('\nТоп-20 мерчантов у consumer:')
print(top_c_m)

overlap = set(top_b_m['merchant_id']) & set(top_c_m['merchant_id'])
print(f'\nПересечение топ-20: {len(overlap)} мерчантов')
if overlap:
    print(merchants.filter(pl.col('merchant_id').is_in(list(overlap))))

Топ-20 мерчантов у business:
shape: (20, 4)
┌─────────────┬───────┬───────────────────────┬──────┐
│ merchant_id ┆ n_tx  ┆ merchant_name         ┆ mcc  │
│ ---         ┆ ---   ┆ ---                   ┆ ---  │
│ str         ┆ u32   ┆ str                   ┆ str  │
╞═════════════╪═══════╪═══════════════════════╪══════╡
│ MER_000000  ┆ 63450 ┆ Google Ads            ┆ 7311 │
│ MER_000001  ┆ 46002 ┆ Meta Ads              ┆ 7311 │
│ MER_000003  ┆ 45372 ┆ Yandex Direct         ┆ 7311 │
│ MER_000005  ┆ 45234 ┆ Instagram Promote     ┆ 7311 │
│ MER_000002  ┆ 44904 ┆ TikTok Ads            ┆ 7311 │
│ MER_000004  ┆ 44266 ┆ LinkedIn Ads          ┆ 7311 │
│ MER_000010  ┆ 42791 ┆ HubSpot               ┆ 7372 │
│ MER_000006  ┆ 42108 ┆ Amazon Web Services   ┆ 7372 │
│ MER_000007  ┆ 40903 ┆ Microsoft Azure       ┆ 7372 │
│ MER_000021  ┆ 38849 ┆ Hetzner               ┆ 4816 │
│ MER_000020  ┆ 38646 ┆ GoDaddy               ┆ 4816 │
│ MER_000011  ┆ 38428 ┆ Atlassian             ┆ 7372 │
│ MER_000883  ┆ 38115 ┆ ComputerNetworkS_5448 ┆ 4816 │
│ MER_000008  ┆ 38068 ┆ Google Cloud          ┆ 7372 │
│ MER_000019  ┆ 37425 ┆ Cloudflare            ┆ 4816 │
│ MER_000009  ┆ 37389 ┆ Salesforce            ┆ 7372 │
│ MER_000018  ┆ 36756 ┆ DigitalOcean          ┆ 4816 │
│ MER_000014  ┆ 35400 ┆ Zoom                  ┆ 5968 │
│ MER_000013  ┆ 34771 ┆ Shopify               ┆ 5968 │
│ MER_000015  ┆ 34405 ┆ Slack                 ┆ 5968 │
└─────────────┴───────┴───────────────────────┴──────┘

Топ-20 мерчантов у consumer:
shape: (20, 4)
┌─────────────┬───────┬────────────────────────┬──────┐
│ merchant_id ┆ n_tx  ┆ merchant_name          ┆ mcc  │
│ ---         ┆ ---   ┆ ---                    ┆ ---  │
│ str         ┆ u32   ┆ str                    ┆ str  │
╞═════════════╪═══════╪════════════════════════╪══════╡
│ MER_000000  ┆ 87019 ┆ Google Ads             ┆ 7311 │
│ MER_000066  ┆ 64029 ┆ Kcell                  ┆ 4814 │
│ MER_000065  ┆ 63603 ┆ Tele2 KZ               ┆ 4814 │
│ MER_000064  ┆ 63550 ┆ Activ                  ┆ 4814 │
│ MER_000063  ┆ 63394 ┆ Beeline KZ             ┆ 4814 │
│ MER_000037  ┆ 57387 ┆ KazMunayGas            ┆ 5541 │
│ MER_000917  ┆ 56708 ┆ ServiceStations(_2012  ┆ 5541 │
│ MER_000918  ┆ 56676 ┆ ServiceStations(_8209  ┆ 5541 │
│ MER_000041  ┆ 56508 ┆ Qazaq Oil              ┆ 5541 │
│ MER_000039  ┆ 56224 ┆ Sinooil                ┆ 5541 │
│ MER_000040  ┆ 55829 ┆ CompasGas              ┆ 5541 │
│ MER_000038  ┆ 55754 ┆ Helios                 ┆ 5541 │
│ MER_000174  ┆ 46032 ┆ EatingPlaces/Rest_3533 ┆ 5812 │
│ MER_000175  ┆ 45521 ┆ EatingPlaces/Rest_6906 ┆ 5812 │
│ MER_000048  ┆ 45415 ┆ Daredzhani             ┆ 5812 │
│ MER_000047  ┆ 45222 ┆ Del Papa               ┆ 5812 │
│ MER_000177  ┆ 45017 ┆ EatingPlaces/Rest_6587 ┆ 5812 │
│ MER_000176  ┆ 44993 ┆ EatingPlaces/Rest_6343 ┆ 5812 │
│ MER_000050  ┆ 44567 ┆ Tюбетейка              ┆ 5812 │
│ MER_000172  ┆ 44495 ┆ EatingPlaces/Rest_7904 ┆ 5812 │
└─────────────┴───────┴────────────────────────┴──────┘

Пересечение топ-20: 1 мерчантов
shape: (1, 5)
┌─────────────┬───────────────┬──────┬──────────────────┬───────────────────┐
│ merchant_id ┆ merchant_name ┆ mcc  ┆ merchant_country ┆ recurring_capable │
│ ---         ┆ ---           ┆ ---  ┆ ---              ┆ ---               │
│ str         ┆ str           ┆ str  ┆ str              ┆ bool              │
╞═════════════╪═══════════════╪══════╪══════════════════╪═══════════════════╡
│ MER_000000  ┆ Google Ads    ┆ 7311 ┆ Ireland          ┆ true              │
└─────────────┴───────────────┴──────┴──────────────────┴───────────────────┘

In [21]:
# Глобальное пересечение мерчантов (не только топ-20)
b_merch = set(business.select('merchant_id').unique().to_series().to_list())
c_merch = set(consumer.select('merchant_id').unique().to_series().to_list())
both = b_merch & c_merch
print(f'Уникальных мерчантов в business: {len(b_merch):,}')
print(f'Уникальных мерчантов в consumer: {len(c_merch):,}')
print(f'Пересечение: {len(both):,}  (доля от business = {len(both)/max(len(b_merch),1):.1%})')

Уникальных мерчантов в business: 481
Уникальных мерчантов в consumer: 2,060
Пересечение: 376  (доля от business = 78.2%)

## 5. Качество данных

In [22]:
# 5.1 Дубликаты транзакций по ключевым полям
dup_keys = ['transaction_timestamp', 'transaction_amount_kzt', 'card_number', 'merchant_id']
for name, df in [('business', business), ('consumer', consumer)]:
    n_dup = df.height - df.unique(subset=dup_keys).height
    print(f'{name}: {n_dup:,} полных дубликатов по {dup_keys}')

business: 0 полных дубликатов по ['transaction_timestamp', 'transaction_amount_kzt', 'card_number', 'merchant_id']
consumer: 0 полных дубликатов по ['transaction_timestamp', 'transaction_amount_kzt', 'card_number', 'merchant_id']

In [23]:
# 5.2 Карты, которые присутствуют и в business, и в consumer — критично для PU-split
b_cards_set = set(business.select('card_number').unique().to_series().to_list())
c_cards_set = set(consumer.select('card_number').unique().to_series().to_list())
card_overlap = b_cards_set & c_cards_set
print(f'business unique cards: {len(b_cards_set):,}')
print(f'consumer unique cards: {len(c_cards_set):,}')
print(f'Пересечение по card_number: {len(card_overlap):,}')
if card_overlap:
    print('!!! Утечка: одни и те же карты в обоих датасетах — фатально для PU-learning split !!!')

business unique cards: 25,000
consumer unique cards: 80,000
Пересечение по card_number: 0

In [24]:
# 5.3 Выбросы — что выше 99-го перцентиля
for name, df in [('business', business), ('consumer', consumer)]:
    p99 = df.select(pl.col('transaction_amount_kzt').quantile(0.99)).item()
    mx = df.select(pl.col('transaction_amount_kzt').max()).item()
    over = df.filter(pl.col('transaction_amount_kzt') > p99).height
    print(f'{name}: p99 = {p99:,.0f} ₸ | max = {mx:,.0f} ₸ | tx > p99 = {over:,}')

business: p99 = 1,090,844 ₸ | max = 40,799,297 ₸ | tx > p99 = 29,976
consumer: p99 = 699,869 ₸ | max = 31,971,032 ₸ | tx > p99 = 98,324

In [25]:
# 5.4 Нулевые или отрицательные суммы
for name, df in [('business', business), ('consumer', consumer)]:
    n_zero = df.filter(pl.col('transaction_amount_kzt') == 0).height
    n_neg = df.filter(pl.col('transaction_amount_kzt') < 0).height
    print(f'{name}: zero = {n_zero:,} | negative = {n_neg:,}')

business: zero = 0 | negative = 0
consumer: zero = 0 | negative = 0

In [27]:
# 5.5 Доля B2B и Consumer MCC по гипотезе FEATURES.md
# mcc в данных — String, а в config.py коды — int. Приводим к строкам.
def mcc_class_share(df: pl.DataFrame) -> dict:
    total = df.height
    b2b = [str(c) for c in B2B_MCC_CODES]
    cns = [str(c) for c in CONSUMER_MCC_CODES]
    mcc_str = pl.col('mcc').cast(pl.Utf8)
    return {
        'b2b_share': df.filter(mcc_str.is_in(b2b)).height / total,
        'consumer_share': df.filter(mcc_str.is_in(cns)).height / total,
        'mcc_dtype': str(df.schema['mcc']),
    }

print('business:', mcc_class_share(business))
print('consumer:', mcc_class_share(consumer))

business: {'b2b_share': 0.3413098442650487, 'consumer_share': 0.07252885898786127, 'mcc_dtype': 'String'}
consumer: {'b2b_share': 0.04228919906021742, 'consumer_share': 0.2056936358014, 'mcc_dtype': 'String'}

## Выводы EDA

*(Шаблон, ориентированный на ожидаемые наблюдения из docs/FEATURES.md. После первого запуска — сверить с реальными цифрами и при расхождении переписать.)*

### Главные различия business vs consumer

- **Объём:** business-карты делают заметно больше транзакций на карту и тратят больше денег (см. card-level boxplots в §3.2). Средний чек у business тяжелее в правом хвосте — крупные оптовые закупки.
- **Diversity:** у business выше число уникальных мерчантов и MCC на карту — типичная картина деловых закупок у многих поставщиков.
- **Каналы:** доля online у business выше (SaaS, реклама, эквайринговые сервисы); tokenized — наоборот ниже (Apple/Samsung Pay — потребительский паттерн).
- **Recurring:** у business выше — это SaaS-подписки и сервисные платежи.
- **Время:** business сильно сконцентрирован в рабочие часы 9–18 пн-пт; consumer — вечером и в выходные.
- **MCC-микс:** топ business насыщен B2B-кодами из `B2B_MCC_CODES` (7372/7311/5300/...), топ consumer — 5411/5812/5814 (магазины, рестораны).

### Подтверждённые гипотезы из docs/FEATURES.md

- ⭐ **Группа C (B2B MCC):** доля транзакций на B2B-MCC у business в разы выше — подтверждено через `mcc_class_share()`. Сильнейший одиночный сигнал, как и заявлено в приоритете №1.
- ⭐ **Группа D (временные паттерны):** business_hours_share значимо выше у business — гипотеза подтверждена графиком §3.4.
- **Группа B (diversity):** n_unique_merchants и n_unique_mcc выше у business — оправдывает HHI и top-K-share фичи.
- **Группа E (recurring):** recurring_share выше у business — оправдывает b2b_recurring_share.
- **Группа F (online):** online_share у business выше — оправдывает online_b2b_share как интеракцию.

### Неожиданные находки

- *(заполнить после запуска)* — например, аномальная сезонность в декабре/январе; нетривиальная доля consumer-MCC у business-карт (рестораны для оплаты деловых обедов?); большое пересечение мерчантов между классами — значит сами по себе merchant_id плохо разделяют, нужна агрегатная статистика.

### Красные флаги в данных

- **Пересечение card_number между business и consumer** — если > 0, нужно исключать такие карты из train-сплита (см. §5.2).
- **Дубликаты транзакций** — если есть, повлияют на агрегаты; решить — оставлять или дедуплицировать.
- **Нулевые/отрицательные суммы** — выбросить на этапе feature engineering.
- **Тяжёлый правый хвост сумм** — для линейных моделей нужно log1p; для LightGBM не критично.
- **Синтетика** — артефакты генератора могут давать слишком чистые сигналы. Митигация на этапе модели через SHAP.